name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]

  workflow_dispatch:

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        config: [Release]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

          - config: Release
            rule: release

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: ${{ matrix.prefix }}-binutils ${{ matrix.prefix }}-make ${{ matrix.prefix }}-${{ matrix.cc }}
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir bin
        make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}   CC=${{ matrix.cc }} USE_SDL=0 USE_VULKAN=1 CNAME=quake3e-vulkan NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}   CC=${{ matrix.cc }} USE_SDL=0 USE_VULKAN_API=0 CNAME=quake3e NO_MAKE_LOCAL=1
        make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}   CC=${{ matrix.cc }} USE_SDL=0 NO_MAKE_LOCAL=1
        if [ ${{ matrix.arch }} == "x86" ]; then
          cp build/release-mingw32-x86/quake3e.exe bin/
          cp build/release-mingw32-x86/quake3e-vulkan.exe bin/
          cp build/release-mingw32-x86/quake3e.ded.exe bin/
        else
          make -f make/lib_q3map2.make clean ${{ matrix.rule }} -j 4  NO_MAKE_LOCAL=1
          make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
          make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 USE_MULTIVM_CLIENT=1 USE_MULTIVM_SERVER=1  NO_MAKE_LOCAL=1
          make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
          make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_MULTIVM_SERVER=1 NO_MAKE_LOCAL=1
          make -f make/game_multi.make clean ${{ matrix.rule }} -j 4     MISSIONPACK=1 BUILD_GAME_QVM=0 NO_MAKE_LOCAL=1
          cp build/release-mingw64-x86_64/quake3e.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e-vulkan.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e.ded.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e_q3map2.x64.dll bin/
          cp build/release-mingw64-x86_64/quake3e.ded_mw.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e.ded_experimental.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e_experimental.x64.exe bin/
          cp build/release-mingw64-x86_64/quake3e_mw.x64.exe bin/
          cp build/release-mingw64-x86_64/multigame/cgame.x64.dll bin/
          cp build/release-mingw64-x86_64/multigame/qagame.x64.dll bin/
          cp build/release-mingw64-x86_64/multigame/ui.x64.dll bin/
        fi

    - uses: actions/upload-artifact@v2
      if: matrix.config == 'Release'
      with:
        name: windows-mingw-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  windows-msvc:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86, x64]
        config: [Release]
        include:
          - arch: arm64
            platform: ARM64
            suffix: .arm64
            pkg_suffix: arm64

          - arch: x86
            platform: Win32
            pkg_suffix: x86

          - arch: x64
            platform: x64
            suffix: .x64
            pkg_suffix: x86_64

    steps:
    - uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir bin

        msbuild code\win32\msvc2017\quake3e-ded.vcxproj -m -p:TargetName=quake3e.ded,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}

        copy code\win32\msvc2017\output\quake3e.ded.exe bin\quake3e.ded${{ matrix.suffix }}.exe

        msbuild code\win32\msvc2017\renderer.vcxproj -m -p:Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild code\win32\msvc2017\quake3e.vcxproj -m -p:TargetName=quake3e,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }},UseWasapi=USE_WASAPI=0

        copy code\win32\msvc2017\output\quake3e.exe bin\quake3e${{ matrix.suffix }}.exe

        msbuild code\win32\msvc2017\renderer.vcxproj -t:Clean -m -p:Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild code\win32\msvc2017\quake3e.vcxproj -t:Clean -m -p:TargetName=quake3e,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}

        msbuild code\win32\msvc2017\renderervk.vcxproj -m -p:Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild code\win32\msvc2017\quake3e.vcxproj -m -p:TargetName=quake3e,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }},UseWasapi=USE_WASAPI=0

        copy code\win32\msvc2017\output\quake3e.exe bin\quake3e-vulkan${{ matrix.suffix }}.exe

    - uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: windows-msvc-${{ matrix.pkg_suffix }}
        path: bin
        if-no-files-found: error
        retention-days: 5
        
  ubuntu-x86:
    name: ${{ matrix.config }} Ubuntu ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        config: [Release]
        include:
          - config: Release
            rule: release
          - arch: x86
            use_sdl: USE_SDL=0
          - arch: x86_64
            use_sdl: USE_SDL=1

    steps:
    - name: Install tools
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install gcc-multilib libcurl4-openssl-dev:i386 mesa-common-dev:i386 libxxf86dga-dev:i386 libxrandr-dev:i386 libxxf86vm-dev:i386 libasound-dev:i386
        else
          sudo apt-get -qq update
          sudo apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev
        fi

    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir bin
        make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN=1 CNAME=quake3e-vulkan NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 NO_MAKE_LOCAL=1
        make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} NO_MAKE_LOCAL=1
        if [ ${{ matrix.arch }} == "x86" ]; then
          cp build/release-linux-x86/quake3e bin/
          cp build/release-linux-x86/quake3e-vulkan bin/
          cp build/release-linux-x86/quake3e.ded bin/
        else
          make -f make/lib_q3map2.make clean ${{ matrix.rule }} -j 4  NO_MAKE_LOCAL=1
          make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
          make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 USE_MULTIVM_CLIENT=1 USE_MULTIVM_SERVER=1  NO_MAKE_LOCAL=1
          make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
          make -f make/build_server.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_MULTIVM_SERVER=1 NO_MAKE_LOCAL=1
          make -f make/lib_q3lcc.make clean ${{ matrix.rule }} -j 4      NO_MAKE_LOCAL=1
          make -f make/game_multi.make clean ${{ matrix.rule }} -j 4     MISSIONPACK=1 NO_MAKE_LOCAL=1
          cp build/release-linux-x86_64/quake3e.x64 bin/
          cp build/release-linux-x86_64/quake3e-vulkan.x64 bin/
          cp build/release-linux-x86_64/quake3e.ded bin/
          cp build/release-linux-x86_64/quake3e_q3map2_x86_64.so bin/
          cp build/release-linux-x86_64/q3lcc bin/
          cp build/release-linux-x86_64/q3asm bin/
          cp build/release-linux-x86_64/q3rcc bin/
          cp build/release-linux-x86_64/q3cpp bin/
          cp build/release-linux-x86_64/lburg/lburg bin/
          cp build/release-linux-x86_64/quake3e.ded_mw bin/
          cp build/release-linux-x86_64/quake3e.ded_experimental bin/
          cp build/release-linux-x86_64/quake3e_experimental bin/
          cp build/release-linux-x86_64/quake3e_mw bin/
          cp build/release-linux-x86_64/multigame/cgamex86_64.so bin/
          cp build/release-linux-x86_64/multigame/qagamex86_64.so bin/
          cp build/release-linux-x86_64/multigame/uix86_64.so bin/
          cp build/release-linux-x86_64/multigame/vm/cgame.qvm bin/
          cp build/release-linux-x86_64/multigame/vm/qagame.qvm bin/
          cp build/release-linux-x86_64/multigame/vm/ui.qvm bin/
        fi

    - uses: actions/upload-artifact@v2
      if: matrix.config == 'Release'
      with:
        name: linux-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  js-js:
    name: ${{ matrix.config }} WebAssembly ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [js]
        cc: [gcc]
        config: [Release]
        include:
          - config: Release
            rule: release
          - arch: js
            use_sdl: USE_SDL=0

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        mkdir libs/linux
        sudo apt-get -qq update
        sudo apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev wget
        wget --no-check-certificate https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/wasi-sdk-14.0-linux.tar.gz
        tar -xf wasi-sdk-14.0-linux.tar.gz -C libs/linux/

    - name: Build
      run: |
        mkdir bin
        make -f make/build_client.make clean ${{ matrix.rule }} -j 8 ARCH=${{ matrix.arch }}    ${{ matrix.use_sdl }} USE_VULKAN_API=0 CNAME=quake3e PLATFORM=js NO_MAKE_LOCAL=1
        cp build/release-js-js/quake3e_js.wasm bin/

    - uses: actions/upload-artifact@v2
      if: matrix.config == 'Release'
      with:
        name: js-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  ubuntu-arm:
    name: ${{ matrix.config }} Ubuntu ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, armv7]
        cc: [gcc]
        config: [Release]
        include:
          - config: Release
            rule: release

    steps:
    - uses: actions/checkout@v2
      if: false

    - name: Build ${{ matrix.arch }}
      uses: uraimo/run-on-arch-action@v2.0.5
      if: false
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        shell: /bin/sh
        run: |
          apt-get -qq update
          apt-get install -y make gcc g++
          apt-get -y install libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev
          make -f make/build_client.make clean ${{ matrix.rule }} -j 4 ARCH=${{ matrix.arch }}    USE_SDL=0 USE_VULKAN=1 CNAME=quake3e-vulkan NO_MAKE_LOCAL=1
          make -f make/build_client.make clean ${{ matrix.rule }} -j 4 ARCH=${{ matrix.arch }}    USE_SDL=0 USE_VULKAN_API=0 CNAME=quake3e NO_MAKE_LOCAL=1

    - uses: actions/upload-artifact@v2
      if: false
      #if: matrix.config == 'Release'
      with:
        name: linux-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  macos-x86:
    name: ${{ matrix.config }} macOS x86_64
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cc: [clang]
        config: [Release]
        include:
          - config: Release
            rule: release

    steps:
    - name: Install tools
      run: brew install coreutils sdl2 glib

    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir bin
        make -f make/build_client.make clean ${{ matrix.rule }} -j 4     RENDERER_DEFAULT=vulkan USE_SDL=1 CNAME=quake3e-vulkan NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 4     USE_VULKAN_API=0 USE_SDL=1 NO_MAKE_LOCAL=1
        make -f make/lib_q3map2.make clean ${{ matrix.rule }} -j 4  NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 4     USE_VULKAN_API=0 USE_SDL=1 USE_MULTIVM_CLIENT=1 USE_MULTIVM_SERVER=1 NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 4     USE_VULKAN_API=0 USE_SDL=1 BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
        make -f make/build_client.make clean ${{ matrix.rule }} -j 4     USE_VULKAN_API=0 USE_SDL=1 NO_MAKE_LOCAL=1 BUILD_SLIM_CLIENT=1
        make -f make/build_server.make clean ${{ matrix.rule }} -j 4     NO_MAKE_LOCAL=1
        make -f make/build_server.make clean ${{ matrix.rule }} -j 4     BUILD_EXPERIMENTAL=1 NO_MAKE_LOCAL=1
        make -f make/build_server.make clean ${{ matrix.rule }} -j 4     USE_MULTIVM_SERVER=1 NO_MAKE_LOCAL=1
        make -f make/game_multi.make clean ${{ matrix.rule }} -j 4     MISSIONPACK=1 BUILD_GAME_QVM=0 NO_MAKE_LOCAL=1
        cp build/release-darwin-x86_64/quake3e bin/
        cp build/release-darwin-x86_64/quake3e_mw bin/
        cp build/release-darwin-x86_64/quake3e_q3map2_x86_64.dylib bin/
        cp build/release-darwin-x86_64/quake3e_experimental bin/
        cp build/release-darwin-x86_64/quake3e_slim bin/
        cp build/release-darwin-x86_64/quake3e.ded bin/
        cp build/release-darwin-x86_64/quake3e.ded_experimental bin/
        cp build/release-darwin-x86_64/quake3e.ded_mw bin/
        cp build/release-darwin-x86_64/quake3e-vulkan bin/
        cp build/release-darwin-x86_64/multigame/cgamex86_64.dylib bin/
        cp build/release-darwin-x86_64/multigame/qagamex86_64.dylib bin/
        cp build/release-darwin-x86_64/multigame/uix86_64.dylib bin/

    - uses: actions/upload-artifact@v2
      if: matrix.config == 'Release'
      with:
        name: macos-${{ matrix.arch }}
        path: bin
        if-no-files-found: error
        retention-days: 5

  create-testing:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [windows-msys, windows-msvc, ubuntu-x86, ubuntu-arm, macos-x86]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Create binary archives
        run: |
          7z a -r quake3e-linux-x86.zip      ./linux-x86/*
          7z a -r quake3e-linux-x86_64.zip   ./linux-x86_64/*
          7z a -r quake3e-windows-mingw-x86.zip    ./windows-mingw-x86/*
          7z a -r quake3e-windows-mingw-x86_64.zip ./windows-mingw-x86_64/*
          7z a -r quake3e-windows-msvc-x86.zip     ./windows-msvc-x86/*
          7z a -r quake3e-windows-msvc-x86_64.zip  ./windows-msvc-x86_64/*
          7z a -r quake3e-windows-msvc-arm64.zip   ./windows-msvc-arm64/*
          7z a -r quake3e-macos-x86_64.zip   ./macos-x86_64/*
          7z a -r quake3e-js.zip   ./js-js/*
#         7z a -r quake3e-linux-aarch64.zip  ./linux-aarch64/*
#         7z a -r quake3e-linux-armv7.zip    ./linux-armv7/*

      - name: Create latest build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            *.zip

  update-release:
    if: ${{ github.event_name == 'release' }}
    needs: [windows-msys, windows-msvc, ubuntu-x86, ubuntu-arm, macos-x86, js-js]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # - artifact_dir: linux-aarch64
          #   artifact_name: quake3e-linux-aarch64.zip

          # - artifact_dir: linux-armv7
          #  artifact_name: quake3e-linux-armv7.zip

          - artifact_dir: linux-x86
            artifact_name: quake3e-linux-x86.zip

          - artifact_dir: linux-x86_64
            artifact_name: quake3e-linux-x86_64.zip

          - artifact_dir: windows-mingw-x86
#           artifact_name: quake3e-windows-mingw-x86.zip
            artifact_name: quake3e-windows-x86.zip 

          - artifact_dir: windows-mingw-x86_64
#           artifact_name: quake3e-windows-mingw-x86_64.zip
            artifact_name: quake3e-windows-x86_64.zip

#         - artifact_dir: windows-msvc-x86
#           artifact_name: quake3e-windows-msvc-x86.zip

#         - artifact_dir: windows-msvc-x86_64
#           artifact_name: quake3e-windows-msvc-x86_64.zip

          - artifact_dir: windows-msvc-arm64
#           artifact_name: quake3e-windows-msvc-arm64.zip
            artifact_name: quake3e-windows-arm64.zip

          - artifact_dir: macos-x86_64
            artifact_name: quake3e-macos-x86_64.zip

          - artifact_dir: js-js
            artifact_name: quake3e-js.zip

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Create archive
        run: 7z a -r ${{ matrix.artifact_name }} ./${{ matrix.artifact_dir }}/*

      - name: Upload archive
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file: ${{ matrix.artifact_name }}
